name: Bug report to project

on:
  issues:
    types: [opened]

jobs:
  add_to_project:
    runs-on: ubuntu-latest
    steps:
      - name: Assign bug report to project
        if: github.event.issue.labels.*.name contains 'bug'
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const projectId = 45;  // Replace with your project ID
            const issueId = context.payload.issue.id;
            await github.projects.createCard({
              column_id: projectId,
              content_id: issueId,
              content_type: 'Issue'
            });
