name: Assign Bug Report to Project

on:
  issues:
    types: [opened]

jobs:
  assign-to-project:
    runs-on: ubuntu-latest
    steps:
      - name: Assign to Project
        uses: actions/github-script@v6
        with:
          script: |
            const issueLabel = 'Bug report';  // Replace with the label used in your bug report template
            const projectId = '45';  // Replace with your project ID
            const columnId = 'f75ad846';  // Replace with the ID of the column in the project

            if (context.payload.issue.labels.some(label => label.name === issueLabel)) {
              await github.projects.createCard({
                column_id: columnId,
                content_id: context.payload.issue.id,
                content_type: 'Issue'
              });
            }
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
